#!/usr/bin/env bash

    function show_usage {
        echo "Usage: $0 source_dir dest_dir"

           }

    #main program start here

    if [ $# -ne 2 ]; then
        show_usage
    else #There are two arguments
        if [ -d $1 ]; then
            source_dir=$1
        else
            echo 'invalid source directory'
            show_usage
        fi

        if [ -d $2 ]; then
            dest_dir=$2
        else
            echo 'invalid destination  directory'
            show_usage
        
        fi
    fi

    printf "source: ${source_dir}\n"
    printf "destination: ${dest_dir}\n"


